services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d winwin_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - win-win

  auth-api:
    build: ./auth-api
    container_name: auth-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - win-win

  data-api:
    build: ./data-api
    container_name: data-api
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - win-win

networks:
  win-win:
    driver: bridge