spring.application.name=auth-api

server.error.include-message=always

base.url.data.api=http://data-api:8081
internal.token=${INTERNAL_TOKEN}

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.security.oauth2.resourceserver.jwt.authorities-claim-name=roles
spring.security.oauth2.resourceserver.jwt.authority-prefix=ROLE_
spring.security.oauth2.resourceserver.jwt.principal-claim-name=preferred_username
spring.security.oauth2.resourceserver.jwt.jws-algorithms=HS256


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
